Numpy Math operations

In [1]:
a= [1,2,3]
b= [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

# This should be reflected on github

In [2]:
import numpy as np

In [3]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [ ]:
a+b  # vectorized operations

# __add__

array([5, 7, 9])

In [5]:
a -b

array([-3, -3, -3])

In [6]:
print(a*b)

[ 4 10 18]


In [7]:
print(a/b)

[0.25 0.4  0.5 ]


# comparison operator

In [8]:
print(a>b)

[False False False]


In [10]:
print(a<b)

[ True  True  True]


In [12]:
print(a==b)

[False False False]


In [13]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
ans = a>b
print(type(ans[0]))

<class 'numpy.bool'>


## Logical Operators

# and , or , not

In [17]:
x= np.array([True, False,True])
y= np.array([False,False,True])

print(np.logical_and(x,y))
print(np.logical_or(x,y))
print(np.logical_not(x))

[False False  True]
[ True False  True]
[False  True False]


# Bitwise operators

In [18]:
a = np.array([1,2,3])
b= np.array([0,1,1])

print(np.bitwise_and(a,b))

[0 0 1]


In [ ]:
# modulus and power

In [19]:
a = np.array([10,20,30])
b = np.array([3,7,4])

In [23]:
print(np.mod(a,b))
print(np.power(a,b))
print(np.remainder(a,b))



[1 6 2]
[      1000 1280000000     810000]
[1 6 2]


# Scalar operations

In [26]:
celcius = np.array([0,10,20,30])

to_farenheit = (9/5 +32)
print(to_farenheit)

33.8


Common Maths functions

In [27]:
a= np.array([1,2,3,4])

print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


# Machine learning

# activation function
# singmoid 



In [30]:
sigmoid = 1 / (1 + np.exp(-x))

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

# Aggregation function s

In [31]:
a= np.array([[1,2,3],
             [4,5,6]])

In [32]:
print(np.sum(a))

21
